### ISSUE TITLE
Other Python program doesn't respect spacing value

### ISSUE THREAD

**Issue by SimonDedman** [pkkid/pygrid#13] opened 2019-03-03 08:00 UTC
I've recently installed the latest version of [catfish](https://launchpad.net/ubuntu/+source/catfish/1.4.7-1), which is python. For some reason this doesn't respect 0 spacing, whereas other programs do. I've rebooted just in case. Any thoughts?
![screenshot_2019-03-06_07-46-56](https://user-images.githubusercontent.com/4599748/53893942-0d50c000-3fe4-11e9-940d-4f79a0b32219.png)

**Comment by pkkid** [comment] 2019-03-15 14:49
This looks like another instance of issue #1. I have trouble getting and using the shadow values from some apps using the gtk+ library. I even opened a bug upstream to see if they can add support for us to get the shadow variables, but they don't want to support the way pygrid using their libraries, and responded with _"GTK is not a window manager toolkit, so it does not offer many functions to get information about foreign windows."_ So unless we find a way to work around this, some specific apps will work like this. :(

Out bug is here: https://github.com/pkkid/pygrid/issues/1
Upstream bug is here: https://bugzilla.gnome.org/show_bug.cgi?id=766496

**Comment by pkkid** [comment] 2019-03-15 14:52
Closing this as a dupe of issue #1 to keep continued conversations in one place. Please add future discussion there.

**Closed by pkkid** 2019-03-15 14:52 UTC
